### ISSUE TITLE
Quick install notes

### ISSUE THREAD

**Issue by Strangemother** [iiegor/chrome-material#5]
I downloaded the github source. This is excellent. I cannot wait to play with it.

I was hoping you could provide a setting started to work with the source; I notice the electron requirements and npm start features - is there anything else?

Additionally; During download, windows 7 will naturally block the inbound-outbound of the unzipped binaries. You need to right-click on the main app and 'unblock'.
I understand it's common sense; but it's not an obvious choice.

Thanks in advance.

**Comment by iiegor** [comment]
Hey @Strangemother!

Yes, it's just that. Otherwise, if you want to build the application by yourself you will need to run `npm run build:[platform]`. I added right now some information in the [README](https://github.com/iiegor/chrome-material#building) to clarify this.

Regarding the second, maybe creating an installer for the application could solve that?
